# Generated by Django 4.0.3 on 2022-03-15 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=128)),
                ('number_of_pages', models.IntegerField()),
                ('author', models.CharField(max_length=128)),
                ('quantity', models.IntegerField()),
                ('published', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
